//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExtraMealMenu
    {
        public int ExtraMealMenuId { get; set; }
        public string ExtraName { get; set; }
        public Nullable<double> ExtraPrice { get; set; }
    }
}
