//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WeeklyMealMenu
    {
        public int WeeklyMealMenuId { get; set; }
        public string Lunch { get; set; }
        public Nullable<double> LunchPrice { get; set; }
        public string Dinner { get; set; }
        public Nullable<double> DinnerPrice { get; set; }
        public Nullable<int> WeekdayId { get; set; }
    
        public virtual Weekday Weekday { get; set; }
    }
}
